[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
credia_reputation = "DUS67qe9NMfLuYr99X21a7NQ12sRHZCpTCDpyGzs4T5o"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/credia_reputation"]

[scripts]
test = "anchor test"
